// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/sensor.proto

package com.google.android.apps.mytracks.content;

public final class Sensor {
  private Sensor() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public enum SensorState
      implements com.google.protobuf.Internal.EnumLite {
    NONE(0, 1),
    CONNECTING(1, 2),
    CONNECTED(2, 3),
    DISCONNECTED(3, 4),
    SENDING(4, 5),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static SensorState valueOf(int value) {
      switch (value) {
        case 1: return NONE;
        case 2: return CONNECTING;
        case 3: return CONNECTED;
        case 4: return DISCONNECTED;
        case 5: return SENDING;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<SensorState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<SensorState>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SensorState>() {
            public SensorState findValueByNumber(int number) {
              return SensorState.valueOf(number)
    ;        }
          };
    
    private final int index;
    private final int value;
    private SensorState(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.google.android.apps.mytracks.content.SensorState)
  }
  
  public static final class SensorData extends
      com.google.protobuf.GeneratedMessageLite {
    // Use SensorData.newBuilder() to construct.
    private SensorData() {
      initFields();
    }
    private SensorData(boolean noInit) {}
    
    private static final SensorData defaultInstance;
    public static SensorData getDefaultInstance() {
      return defaultInstance;
    }
    
    public SensorData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // required .com.google.android.apps.mytracks.content.SensorState state = 1 [default = NONE];
    public static final int STATE_FIELD_NUMBER = 1;
    private boolean hasState;
    private com.google.android.apps.mytracks.content.Sensor.SensorState state_;
    public boolean hasState() { return hasState; }
    public com.google.android.apps.mytracks.content.Sensor.SensorState getState() { return state_; }
    
    // optional int32 value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private boolean hasValue;
    private int value_ = 0;
    public boolean hasValue() { return hasValue; }
    public int getValue() { return value_; }
    
    private void initFields() {
      state_ = com.google.android.apps.mytracks.content.Sensor.SensorState.NONE;
    }
    public final boolean isInitialized() {
      if (!hasState) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasState()) {
        output.writeEnum(1, getState().getNumber());
      }
      if (hasValue()) {
        output.writeInt32(2, getValue());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasState()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getState().getNumber());
      }
      if (hasValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getValue());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.android.apps.mytracks.content.Sensor.SensorData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.android.apps.mytracks.content.Sensor.SensorData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.android.apps.mytracks.content.Sensor.SensorData, Builder> {
      private com.google.android.apps.mytracks.content.Sensor.SensorData result;
      
      // Construct using com.google.android.apps.mytracks.content.Sensor.SensorData.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.android.apps.mytracks.content.Sensor.SensorData();
        return builder;
      }
      
      protected com.google.android.apps.mytracks.content.Sensor.SensorData internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.android.apps.mytracks.content.Sensor.SensorData();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.android.apps.mytracks.content.Sensor.SensorData getDefaultInstanceForType() {
        return com.google.android.apps.mytracks.content.Sensor.SensorData.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.android.apps.mytracks.content.Sensor.SensorData build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.android.apps.mytracks.content.Sensor.SensorData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.android.apps.mytracks.content.Sensor.SensorData buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.google.android.apps.mytracks.content.Sensor.SensorData returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.android.apps.mytracks.content.Sensor.SensorData other) {
        if (other == com.google.android.apps.mytracks.content.Sensor.SensorData.getDefaultInstance()) return this;
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.google.android.apps.mytracks.content.Sensor.SensorState value = com.google.android.apps.mytracks.content.Sensor.SensorState.valueOf(rawValue);
              if (value != null) {
                setState(value);
              }
              break;
            }
            case 16: {
              setValue(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required .com.google.android.apps.mytracks.content.SensorState state = 1 [default = NONE];
      public boolean hasState() {
        return result.hasState();
      }
      public com.google.android.apps.mytracks.content.Sensor.SensorState getState() {
        return result.getState();
      }
      public Builder setState(com.google.android.apps.mytracks.content.Sensor.SensorState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasState = true;
        result.state_ = value;
        return this;
      }
      public Builder clearState() {
        result.hasState = false;
        result.state_ = com.google.android.apps.mytracks.content.Sensor.SensorState.NONE;
        return this;
      }
      
      // optional int32 value = 2;
      public boolean hasValue() {
        return result.hasValue();
      }
      public int getValue() {
        return result.getValue();
      }
      public Builder setValue(int value) {
        result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.google.android.apps.mytracks.content.SensorData)
    }
    
    static {
      defaultInstance = new SensorData(true);
      com.google.android.apps.mytracks.content.Sensor.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.android.apps.mytracks.content.SensorData)
  }
  
  public static final class SensorDataDouble extends
      com.google.protobuf.GeneratedMessageLite {
    // Use SensorDataDouble.newBuilder() to construct.
    private SensorDataDouble() {
      initFields();
    }
    private SensorDataDouble(boolean noInit) {}
    
    private static final SensorDataDouble defaultInstance;
    public static SensorDataDouble getDefaultInstance() {
      return defaultInstance;
    }
    
    public SensorDataDouble getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // required .com.google.android.apps.mytracks.content.SensorState state = 1 [default = NONE];
    public static final int STATE_FIELD_NUMBER = 1;
    private boolean hasState;
    private com.google.android.apps.mytracks.content.Sensor.SensorState state_;
    public boolean hasState() { return hasState; }
    public com.google.android.apps.mytracks.content.Sensor.SensorState getState() { return state_; }
    
    // optional int64 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private boolean hasTimestamp;
    private long timestamp_ = 0L;
    public boolean hasTimestamp() { return hasTimestamp; }
    public long getTimestamp() { return timestamp_; }
    
    // optional double value = 3;
    public static final int VALUE_FIELD_NUMBER = 3;
    private boolean hasValue;
    private double value_ = 0D;
    public boolean hasValue() { return hasValue; }
    public double getValue() { return value_; }
    
    private void initFields() {
      state_ = com.google.android.apps.mytracks.content.Sensor.SensorState.NONE;
    }
    public final boolean isInitialized() {
      if (!hasState) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasState()) {
        output.writeEnum(1, getState().getNumber());
      }
      if (hasTimestamp()) {
        output.writeInt64(2, getTimestamp());
      }
      if (hasValue()) {
        output.writeDouble(3, getValue());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasState()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getState().getNumber());
      }
      if (hasTimestamp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getTimestamp());
      }
      if (hasValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, getValue());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataDouble parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataDouble parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataDouble parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataDouble parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataDouble parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataDouble parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataDouble parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataDouble parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataDouble parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataDouble parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.android.apps.mytracks.content.Sensor.SensorDataDouble prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.android.apps.mytracks.content.Sensor.SensorDataDouble, Builder> {
      private com.google.android.apps.mytracks.content.Sensor.SensorDataDouble result;
      
      // Construct using com.google.android.apps.mytracks.content.Sensor.SensorDataDouble.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.android.apps.mytracks.content.Sensor.SensorDataDouble();
        return builder;
      }
      
      protected com.google.android.apps.mytracks.content.Sensor.SensorDataDouble internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.android.apps.mytracks.content.Sensor.SensorDataDouble();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.android.apps.mytracks.content.Sensor.SensorDataDouble getDefaultInstanceForType() {
        return com.google.android.apps.mytracks.content.Sensor.SensorDataDouble.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.android.apps.mytracks.content.Sensor.SensorDataDouble build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.android.apps.mytracks.content.Sensor.SensorDataDouble buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.android.apps.mytracks.content.Sensor.SensorDataDouble buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.google.android.apps.mytracks.content.Sensor.SensorDataDouble returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.android.apps.mytracks.content.Sensor.SensorDataDouble other) {
        if (other == com.google.android.apps.mytracks.content.Sensor.SensorDataDouble.getDefaultInstance()) return this;
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.google.android.apps.mytracks.content.Sensor.SensorState value = com.google.android.apps.mytracks.content.Sensor.SensorState.valueOf(rawValue);
              if (value != null) {
                setState(value);
              }
              break;
            }
            case 16: {
              setTimestamp(input.readInt64());
              break;
            }
            case 25: {
              setValue(input.readDouble());
              break;
            }
          }
        }
      }
      
      
      // required .com.google.android.apps.mytracks.content.SensorState state = 1 [default = NONE];
      public boolean hasState() {
        return result.hasState();
      }
      public com.google.android.apps.mytracks.content.Sensor.SensorState getState() {
        return result.getState();
      }
      public Builder setState(com.google.android.apps.mytracks.content.Sensor.SensorState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasState = true;
        result.state_ = value;
        return this;
      }
      public Builder clearState() {
        result.hasState = false;
        result.state_ = com.google.android.apps.mytracks.content.Sensor.SensorState.NONE;
        return this;
      }
      
      // optional int64 timestamp = 2;
      public boolean hasTimestamp() {
        return result.hasTimestamp();
      }
      public long getTimestamp() {
        return result.getTimestamp();
      }
      public Builder setTimestamp(long value) {
        result.hasTimestamp = true;
        result.timestamp_ = value;
        return this;
      }
      public Builder clearTimestamp() {
        result.hasTimestamp = false;
        result.timestamp_ = 0L;
        return this;
      }
      
      // optional double value = 3;
      public boolean hasValue() {
        return result.hasValue();
      }
      public double getValue() {
        return result.getValue();
      }
      public Builder setValue(double value) {
        result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = 0D;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.google.android.apps.mytracks.content.SensorDataDouble)
    }
    
    static {
      defaultInstance = new SensorDataDouble(true);
      com.google.android.apps.mytracks.content.Sensor.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.android.apps.mytracks.content.SensorDataDouble)
  }
  
  public static final class SensorDataTriple extends
      com.google.protobuf.GeneratedMessageLite {
    // Use SensorDataTriple.newBuilder() to construct.
    private SensorDataTriple() {
      initFields();
    }
    private SensorDataTriple(boolean noInit) {}
    
    private static final SensorDataTriple defaultInstance;
    public static SensorDataTriple getDefaultInstance() {
      return defaultInstance;
    }
    
    public SensorDataTriple getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // required .com.google.android.apps.mytracks.content.SensorState state = 1 [default = NONE];
    public static final int STATE_FIELD_NUMBER = 1;
    private boolean hasState;
    private com.google.android.apps.mytracks.content.Sensor.SensorState state_;
    public boolean hasState() { return hasState; }
    public com.google.android.apps.mytracks.content.Sensor.SensorState getState() { return state_; }
    
    // optional int64 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private boolean hasTimestamp;
    private long timestamp_ = 0L;
    public boolean hasTimestamp() { return hasTimestamp; }
    public long getTimestamp() { return timestamp_; }
    
    // optional double x = 3;
    public static final int X_FIELD_NUMBER = 3;
    private boolean hasX;
    private double x_ = 0D;
    public boolean hasX() { return hasX; }
    public double getX() { return x_; }
    
    // optional double y = 4;
    public static final int Y_FIELD_NUMBER = 4;
    private boolean hasY;
    private double y_ = 0D;
    public boolean hasY() { return hasY; }
    public double getY() { return y_; }
    
    // optional double z = 5;
    public static final int Z_FIELD_NUMBER = 5;
    private boolean hasZ;
    private double z_ = 0D;
    public boolean hasZ() { return hasZ; }
    public double getZ() { return z_; }
    
    private void initFields() {
      state_ = com.google.android.apps.mytracks.content.Sensor.SensorState.NONE;
    }
    public final boolean isInitialized() {
      if (!hasState) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasState()) {
        output.writeEnum(1, getState().getNumber());
      }
      if (hasTimestamp()) {
        output.writeInt64(2, getTimestamp());
      }
      if (hasX()) {
        output.writeDouble(3, getX());
      }
      if (hasY()) {
        output.writeDouble(4, getY());
      }
      if (hasZ()) {
        output.writeDouble(5, getZ());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasState()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getState().getNumber());
      }
      if (hasTimestamp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getTimestamp());
      }
      if (hasX()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, getX());
      }
      if (hasY()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, getY());
      }
      if (hasZ()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, getZ());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataTriple parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataTriple parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataTriple parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataTriple parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataTriple parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataTriple parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataTriple parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataTriple parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataTriple parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataTriple parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.android.apps.mytracks.content.Sensor.SensorDataTriple prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.android.apps.mytracks.content.Sensor.SensorDataTriple, Builder> {
      private com.google.android.apps.mytracks.content.Sensor.SensorDataTriple result;
      
      // Construct using com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.android.apps.mytracks.content.Sensor.SensorDataTriple();
        return builder;
      }
      
      protected com.google.android.apps.mytracks.content.Sensor.SensorDataTriple internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.android.apps.mytracks.content.Sensor.SensorDataTriple();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.android.apps.mytracks.content.Sensor.SensorDataTriple getDefaultInstanceForType() {
        return com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.android.apps.mytracks.content.Sensor.SensorDataTriple build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.android.apps.mytracks.content.Sensor.SensorDataTriple buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.android.apps.mytracks.content.Sensor.SensorDataTriple buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.google.android.apps.mytracks.content.Sensor.SensorDataTriple returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.android.apps.mytracks.content.Sensor.SensorDataTriple other) {
        if (other == com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.getDefaultInstance()) return this;
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.google.android.apps.mytracks.content.Sensor.SensorState value = com.google.android.apps.mytracks.content.Sensor.SensorState.valueOf(rawValue);
              if (value != null) {
                setState(value);
              }
              break;
            }
            case 16: {
              setTimestamp(input.readInt64());
              break;
            }
            case 25: {
              setX(input.readDouble());
              break;
            }
            case 33: {
              setY(input.readDouble());
              break;
            }
            case 41: {
              setZ(input.readDouble());
              break;
            }
          }
        }
      }
      
      
      // required .com.google.android.apps.mytracks.content.SensorState state = 1 [default = NONE];
      public boolean hasState() {
        return result.hasState();
      }
      public com.google.android.apps.mytracks.content.Sensor.SensorState getState() {
        return result.getState();
      }
      public Builder setState(com.google.android.apps.mytracks.content.Sensor.SensorState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasState = true;
        result.state_ = value;
        return this;
      }
      public Builder clearState() {
        result.hasState = false;
        result.state_ = com.google.android.apps.mytracks.content.Sensor.SensorState.NONE;
        return this;
      }
      
      // optional int64 timestamp = 2;
      public boolean hasTimestamp() {
        return result.hasTimestamp();
      }
      public long getTimestamp() {
        return result.getTimestamp();
      }
      public Builder setTimestamp(long value) {
        result.hasTimestamp = true;
        result.timestamp_ = value;
        return this;
      }
      public Builder clearTimestamp() {
        result.hasTimestamp = false;
        result.timestamp_ = 0L;
        return this;
      }
      
      // optional double x = 3;
      public boolean hasX() {
        return result.hasX();
      }
      public double getX() {
        return result.getX();
      }
      public Builder setX(double value) {
        result.hasX = true;
        result.x_ = value;
        return this;
      }
      public Builder clearX() {
        result.hasX = false;
        result.x_ = 0D;
        return this;
      }
      
      // optional double y = 4;
      public boolean hasY() {
        return result.hasY();
      }
      public double getY() {
        return result.getY();
      }
      public Builder setY(double value) {
        result.hasY = true;
        result.y_ = value;
        return this;
      }
      public Builder clearY() {
        result.hasY = false;
        result.y_ = 0D;
        return this;
      }
      
      // optional double z = 5;
      public boolean hasZ() {
        return result.hasZ();
      }
      public double getZ() {
        return result.getZ();
      }
      public Builder setZ(double value) {
        result.hasZ = true;
        result.z_ = value;
        return this;
      }
      public Builder clearZ() {
        result.hasZ = false;
        result.z_ = 0D;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.google.android.apps.mytracks.content.SensorDataTriple)
    }
    
    static {
      defaultInstance = new SensorDataTriple(true);
      com.google.android.apps.mytracks.content.Sensor.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.android.apps.mytracks.content.SensorDataTriple)
  }
  
  public static final class SensorDataSet extends
      com.google.protobuf.GeneratedMessageLite {
    // Use SensorDataSet.newBuilder() to construct.
    private SensorDataSet() {
      initFields();
    }
    private SensorDataSet(boolean noInit) {}
    
    private static final SensorDataSet defaultInstance;
    public static SensorDataSet getDefaultInstance() {
      return defaultInstance;
    }
    
    public SensorDataSet getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // optional uint64 creation_time = 1 [default = 0];
    public static final int CREATION_TIME_FIELD_NUMBER = 1;
    private boolean hasCreationTime;
    private long creationTime_ = 0L;
    public boolean hasCreationTime() { return hasCreationTime; }
    public long getCreationTime() { return creationTime_; }
    
    // optional .com.google.android.apps.mytracks.content.SensorData heart_rate = 2;
    public static final int HEART_RATE_FIELD_NUMBER = 2;
    private boolean hasHeartRate;
    private com.google.android.apps.mytracks.content.Sensor.SensorData heartRate_;
    public boolean hasHeartRate() { return hasHeartRate; }
    public com.google.android.apps.mytracks.content.Sensor.SensorData getHeartRate() { return heartRate_; }
    
    // optional .com.google.android.apps.mytracks.content.SensorData cadence = 3;
    public static final int CADENCE_FIELD_NUMBER = 3;
    private boolean hasCadence;
    private com.google.android.apps.mytracks.content.Sensor.SensorData cadence_;
    public boolean hasCadence() { return hasCadence; }
    public com.google.android.apps.mytracks.content.Sensor.SensorData getCadence() { return cadence_; }
    
    // optional .com.google.android.apps.mytracks.content.SensorData power = 4;
    public static final int POWER_FIELD_NUMBER = 4;
    private boolean hasPower;
    private com.google.android.apps.mytracks.content.Sensor.SensorData power_;
    public boolean hasPower() { return hasPower; }
    public com.google.android.apps.mytracks.content.Sensor.SensorData getPower() { return power_; }
    
    // optional .com.google.android.apps.mytracks.content.SensorData battery_level = 5;
    public static final int BATTERY_LEVEL_FIELD_NUMBER = 5;
    private boolean hasBatteryLevel;
    private com.google.android.apps.mytracks.content.Sensor.SensorData batteryLevel_;
    public boolean hasBatteryLevel() { return hasBatteryLevel; }
    public com.google.android.apps.mytracks.content.Sensor.SensorData getBatteryLevel() { return batteryLevel_; }
    
    // optional .com.google.android.apps.mytracks.content.SensorDataDouble speed = 6;
    public static final int SPEED_FIELD_NUMBER = 6;
    private boolean hasSpeed;
    private com.google.android.apps.mytracks.content.Sensor.SensorDataDouble speed_;
    public boolean hasSpeed() { return hasSpeed; }
    public com.google.android.apps.mytracks.content.Sensor.SensorDataDouble getSpeed() { return speed_; }
    
    // optional .com.google.android.apps.mytracks.content.SensorDataTriple accel = 7;
    public static final int ACCEL_FIELD_NUMBER = 7;
    private boolean hasAccel;
    private com.google.android.apps.mytracks.content.Sensor.SensorDataTriple accel_;
    public boolean hasAccel() { return hasAccel; }
    public com.google.android.apps.mytracks.content.Sensor.SensorDataTriple getAccel() { return accel_; }
    
    // optional .com.google.android.apps.mytracks.content.SensorDataTriple magnetic_field = 8;
    public static final int MAGNETIC_FIELD_FIELD_NUMBER = 8;
    private boolean hasMagneticField;
    private com.google.android.apps.mytracks.content.Sensor.SensorDataTriple magneticField_;
    public boolean hasMagneticField() { return hasMagneticField; }
    public com.google.android.apps.mytracks.content.Sensor.SensorDataTriple getMagneticField() { return magneticField_; }
    
    // optional .com.google.android.apps.mytracks.content.SensorDataTriple gyro = 9;
    public static final int GYRO_FIELD_NUMBER = 9;
    private boolean hasGyro;
    private com.google.android.apps.mytracks.content.Sensor.SensorDataTriple gyro_;
    public boolean hasGyro() { return hasGyro; }
    public com.google.android.apps.mytracks.content.Sensor.SensorDataTriple getGyro() { return gyro_; }
    
    // optional .com.google.android.apps.mytracks.content.SensorDataTriple gravity = 10;
    public static final int GRAVITY_FIELD_NUMBER = 10;
    private boolean hasGravity;
    private com.google.android.apps.mytracks.content.Sensor.SensorDataTriple gravity_;
    public boolean hasGravity() { return hasGravity; }
    public com.google.android.apps.mytracks.content.Sensor.SensorDataTriple getGravity() { return gravity_; }
    
    private void initFields() {
      heartRate_ = com.google.android.apps.mytracks.content.Sensor.SensorData.getDefaultInstance();
      cadence_ = com.google.android.apps.mytracks.content.Sensor.SensorData.getDefaultInstance();
      power_ = com.google.android.apps.mytracks.content.Sensor.SensorData.getDefaultInstance();
      batteryLevel_ = com.google.android.apps.mytracks.content.Sensor.SensorData.getDefaultInstance();
      speed_ = com.google.android.apps.mytracks.content.Sensor.SensorDataDouble.getDefaultInstance();
      accel_ = com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.getDefaultInstance();
      magneticField_ = com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.getDefaultInstance();
      gyro_ = com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.getDefaultInstance();
      gravity_ = com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (hasHeartRate()) {
        if (!getHeartRate().isInitialized()) return false;
      }
      if (hasCadence()) {
        if (!getCadence().isInitialized()) return false;
      }
      if (hasPower()) {
        if (!getPower().isInitialized()) return false;
      }
      if (hasBatteryLevel()) {
        if (!getBatteryLevel().isInitialized()) return false;
      }
      if (hasSpeed()) {
        if (!getSpeed().isInitialized()) return false;
      }
      if (hasAccel()) {
        if (!getAccel().isInitialized()) return false;
      }
      if (hasMagneticField()) {
        if (!getMagneticField().isInitialized()) return false;
      }
      if (hasGyro()) {
        if (!getGyro().isInitialized()) return false;
      }
      if (hasGravity()) {
        if (!getGravity().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasCreationTime()) {
        output.writeUInt64(1, getCreationTime());
      }
      if (hasHeartRate()) {
        output.writeMessage(2, getHeartRate());
      }
      if (hasCadence()) {
        output.writeMessage(3, getCadence());
      }
      if (hasPower()) {
        output.writeMessage(4, getPower());
      }
      if (hasBatteryLevel()) {
        output.writeMessage(5, getBatteryLevel());
      }
      if (hasSpeed()) {
        output.writeMessage(6, getSpeed());
      }
      if (hasAccel()) {
        output.writeMessage(7, getAccel());
      }
      if (hasMagneticField()) {
        output.writeMessage(8, getMagneticField());
      }
      if (hasGyro()) {
        output.writeMessage(9, getGyro());
      }
      if (hasGravity()) {
        output.writeMessage(10, getGravity());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCreationTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, getCreationTime());
      }
      if (hasHeartRate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getHeartRate());
      }
      if (hasCadence()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getCadence());
      }
      if (hasPower()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getPower());
      }
      if (hasBatteryLevel()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getBatteryLevel());
      }
      if (hasSpeed()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getSpeed());
      }
      if (hasAccel()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getAccel());
      }
      if (hasMagneticField()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getMagneticField());
      }
      if (hasGyro()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getGyro());
      }
      if (hasGravity()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, getGravity());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataSet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataSet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataSet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataSet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataSet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataSet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataSet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataSet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataSet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.google.android.apps.mytracks.content.Sensor.SensorDataSet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.android.apps.mytracks.content.Sensor.SensorDataSet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.android.apps.mytracks.content.Sensor.SensorDataSet, Builder> {
      private com.google.android.apps.mytracks.content.Sensor.SensorDataSet result;
      
      // Construct using com.google.android.apps.mytracks.content.Sensor.SensorDataSet.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.google.android.apps.mytracks.content.Sensor.SensorDataSet();
        return builder;
      }
      
      protected com.google.android.apps.mytracks.content.Sensor.SensorDataSet internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.google.android.apps.mytracks.content.Sensor.SensorDataSet();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.android.apps.mytracks.content.Sensor.SensorDataSet getDefaultInstanceForType() {
        return com.google.android.apps.mytracks.content.Sensor.SensorDataSet.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.google.android.apps.mytracks.content.Sensor.SensorDataSet build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.google.android.apps.mytracks.content.Sensor.SensorDataSet buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.google.android.apps.mytracks.content.Sensor.SensorDataSet buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.google.android.apps.mytracks.content.Sensor.SensorDataSet returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.android.apps.mytracks.content.Sensor.SensorDataSet other) {
        if (other == com.google.android.apps.mytracks.content.Sensor.SensorDataSet.getDefaultInstance()) return this;
        if (other.hasCreationTime()) {
          setCreationTime(other.getCreationTime());
        }
        if (other.hasHeartRate()) {
          mergeHeartRate(other.getHeartRate());
        }
        if (other.hasCadence()) {
          mergeCadence(other.getCadence());
        }
        if (other.hasPower()) {
          mergePower(other.getPower());
        }
        if (other.hasBatteryLevel()) {
          mergeBatteryLevel(other.getBatteryLevel());
        }
        if (other.hasSpeed()) {
          mergeSpeed(other.getSpeed());
        }
        if (other.hasAccel()) {
          mergeAccel(other.getAccel());
        }
        if (other.hasMagneticField()) {
          mergeMagneticField(other.getMagneticField());
        }
        if (other.hasGyro()) {
          mergeGyro(other.getGyro());
        }
        if (other.hasGravity()) {
          mergeGravity(other.getGravity());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              setCreationTime(input.readUInt64());
              break;
            }
            case 18: {
              com.google.android.apps.mytracks.content.Sensor.SensorData.Builder subBuilder = com.google.android.apps.mytracks.content.Sensor.SensorData.newBuilder();
              if (hasHeartRate()) {
                subBuilder.mergeFrom(getHeartRate());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setHeartRate(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.google.android.apps.mytracks.content.Sensor.SensorData.Builder subBuilder = com.google.android.apps.mytracks.content.Sensor.SensorData.newBuilder();
              if (hasCadence()) {
                subBuilder.mergeFrom(getCadence());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCadence(subBuilder.buildPartial());
              break;
            }
            case 34: {
              com.google.android.apps.mytracks.content.Sensor.SensorData.Builder subBuilder = com.google.android.apps.mytracks.content.Sensor.SensorData.newBuilder();
              if (hasPower()) {
                subBuilder.mergeFrom(getPower());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPower(subBuilder.buildPartial());
              break;
            }
            case 42: {
              com.google.android.apps.mytracks.content.Sensor.SensorData.Builder subBuilder = com.google.android.apps.mytracks.content.Sensor.SensorData.newBuilder();
              if (hasBatteryLevel()) {
                subBuilder.mergeFrom(getBatteryLevel());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setBatteryLevel(subBuilder.buildPartial());
              break;
            }
            case 50: {
              com.google.android.apps.mytracks.content.Sensor.SensorDataDouble.Builder subBuilder = com.google.android.apps.mytracks.content.Sensor.SensorDataDouble.newBuilder();
              if (hasSpeed()) {
                subBuilder.mergeFrom(getSpeed());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSpeed(subBuilder.buildPartial());
              break;
            }
            case 58: {
              com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.Builder subBuilder = com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.newBuilder();
              if (hasAccel()) {
                subBuilder.mergeFrom(getAccel());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setAccel(subBuilder.buildPartial());
              break;
            }
            case 66: {
              com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.Builder subBuilder = com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.newBuilder();
              if (hasMagneticField()) {
                subBuilder.mergeFrom(getMagneticField());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMagneticField(subBuilder.buildPartial());
              break;
            }
            case 74: {
              com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.Builder subBuilder = com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.newBuilder();
              if (hasGyro()) {
                subBuilder.mergeFrom(getGyro());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGyro(subBuilder.buildPartial());
              break;
            }
            case 82: {
              com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.Builder subBuilder = com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.newBuilder();
              if (hasGravity()) {
                subBuilder.mergeFrom(getGravity());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGravity(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional uint64 creation_time = 1 [default = 0];
      public boolean hasCreationTime() {
        return result.hasCreationTime();
      }
      public long getCreationTime() {
        return result.getCreationTime();
      }
      public Builder setCreationTime(long value) {
        result.hasCreationTime = true;
        result.creationTime_ = value;
        return this;
      }
      public Builder clearCreationTime() {
        result.hasCreationTime = false;
        result.creationTime_ = 0L;
        return this;
      }
      
      // optional .com.google.android.apps.mytracks.content.SensorData heart_rate = 2;
      public boolean hasHeartRate() {
        return result.hasHeartRate();
      }
      public com.google.android.apps.mytracks.content.Sensor.SensorData getHeartRate() {
        return result.getHeartRate();
      }
      public Builder setHeartRate(com.google.android.apps.mytracks.content.Sensor.SensorData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasHeartRate = true;
        result.heartRate_ = value;
        return this;
      }
      public Builder setHeartRate(com.google.android.apps.mytracks.content.Sensor.SensorData.Builder builderForValue) {
        result.hasHeartRate = true;
        result.heartRate_ = builderForValue.build();
        return this;
      }
      public Builder mergeHeartRate(com.google.android.apps.mytracks.content.Sensor.SensorData value) {
        if (result.hasHeartRate() &&
            result.heartRate_ != com.google.android.apps.mytracks.content.Sensor.SensorData.getDefaultInstance()) {
          result.heartRate_ =
            com.google.android.apps.mytracks.content.Sensor.SensorData.newBuilder(result.heartRate_).mergeFrom(value).buildPartial();
        } else {
          result.heartRate_ = value;
        }
        result.hasHeartRate = true;
        return this;
      }
      public Builder clearHeartRate() {
        result.hasHeartRate = false;
        result.heartRate_ = com.google.android.apps.mytracks.content.Sensor.SensorData.getDefaultInstance();
        return this;
      }
      
      // optional .com.google.android.apps.mytracks.content.SensorData cadence = 3;
      public boolean hasCadence() {
        return result.hasCadence();
      }
      public com.google.android.apps.mytracks.content.Sensor.SensorData getCadence() {
        return result.getCadence();
      }
      public Builder setCadence(com.google.android.apps.mytracks.content.Sensor.SensorData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasCadence = true;
        result.cadence_ = value;
        return this;
      }
      public Builder setCadence(com.google.android.apps.mytracks.content.Sensor.SensorData.Builder builderForValue) {
        result.hasCadence = true;
        result.cadence_ = builderForValue.build();
        return this;
      }
      public Builder mergeCadence(com.google.android.apps.mytracks.content.Sensor.SensorData value) {
        if (result.hasCadence() &&
            result.cadence_ != com.google.android.apps.mytracks.content.Sensor.SensorData.getDefaultInstance()) {
          result.cadence_ =
            com.google.android.apps.mytracks.content.Sensor.SensorData.newBuilder(result.cadence_).mergeFrom(value).buildPartial();
        } else {
          result.cadence_ = value;
        }
        result.hasCadence = true;
        return this;
      }
      public Builder clearCadence() {
        result.hasCadence = false;
        result.cadence_ = com.google.android.apps.mytracks.content.Sensor.SensorData.getDefaultInstance();
        return this;
      }
      
      // optional .com.google.android.apps.mytracks.content.SensorData power = 4;
      public boolean hasPower() {
        return result.hasPower();
      }
      public com.google.android.apps.mytracks.content.Sensor.SensorData getPower() {
        return result.getPower();
      }
      public Builder setPower(com.google.android.apps.mytracks.content.Sensor.SensorData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasPower = true;
        result.power_ = value;
        return this;
      }
      public Builder setPower(com.google.android.apps.mytracks.content.Sensor.SensorData.Builder builderForValue) {
        result.hasPower = true;
        result.power_ = builderForValue.build();
        return this;
      }
      public Builder mergePower(com.google.android.apps.mytracks.content.Sensor.SensorData value) {
        if (result.hasPower() &&
            result.power_ != com.google.android.apps.mytracks.content.Sensor.SensorData.getDefaultInstance()) {
          result.power_ =
            com.google.android.apps.mytracks.content.Sensor.SensorData.newBuilder(result.power_).mergeFrom(value).buildPartial();
        } else {
          result.power_ = value;
        }
        result.hasPower = true;
        return this;
      }
      public Builder clearPower() {
        result.hasPower = false;
        result.power_ = com.google.android.apps.mytracks.content.Sensor.SensorData.getDefaultInstance();
        return this;
      }
      
      // optional .com.google.android.apps.mytracks.content.SensorData battery_level = 5;
      public boolean hasBatteryLevel() {
        return result.hasBatteryLevel();
      }
      public com.google.android.apps.mytracks.content.Sensor.SensorData getBatteryLevel() {
        return result.getBatteryLevel();
      }
      public Builder setBatteryLevel(com.google.android.apps.mytracks.content.Sensor.SensorData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasBatteryLevel = true;
        result.batteryLevel_ = value;
        return this;
      }
      public Builder setBatteryLevel(com.google.android.apps.mytracks.content.Sensor.SensorData.Builder builderForValue) {
        result.hasBatteryLevel = true;
        result.batteryLevel_ = builderForValue.build();
        return this;
      }
      public Builder mergeBatteryLevel(com.google.android.apps.mytracks.content.Sensor.SensorData value) {
        if (result.hasBatteryLevel() &&
            result.batteryLevel_ != com.google.android.apps.mytracks.content.Sensor.SensorData.getDefaultInstance()) {
          result.batteryLevel_ =
            com.google.android.apps.mytracks.content.Sensor.SensorData.newBuilder(result.batteryLevel_).mergeFrom(value).buildPartial();
        } else {
          result.batteryLevel_ = value;
        }
        result.hasBatteryLevel = true;
        return this;
      }
      public Builder clearBatteryLevel() {
        result.hasBatteryLevel = false;
        result.batteryLevel_ = com.google.android.apps.mytracks.content.Sensor.SensorData.getDefaultInstance();
        return this;
      }
      
      // optional .com.google.android.apps.mytracks.content.SensorDataDouble speed = 6;
      public boolean hasSpeed() {
        return result.hasSpeed();
      }
      public com.google.android.apps.mytracks.content.Sensor.SensorDataDouble getSpeed() {
        return result.getSpeed();
      }
      public Builder setSpeed(com.google.android.apps.mytracks.content.Sensor.SensorDataDouble value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasSpeed = true;
        result.speed_ = value;
        return this;
      }
      public Builder setSpeed(com.google.android.apps.mytracks.content.Sensor.SensorDataDouble.Builder builderForValue) {
        result.hasSpeed = true;
        result.speed_ = builderForValue.build();
        return this;
      }
      public Builder mergeSpeed(com.google.android.apps.mytracks.content.Sensor.SensorDataDouble value) {
        if (result.hasSpeed() &&
            result.speed_ != com.google.android.apps.mytracks.content.Sensor.SensorDataDouble.getDefaultInstance()) {
          result.speed_ =
            com.google.android.apps.mytracks.content.Sensor.SensorDataDouble.newBuilder(result.speed_).mergeFrom(value).buildPartial();
        } else {
          result.speed_ = value;
        }
        result.hasSpeed = true;
        return this;
      }
      public Builder clearSpeed() {
        result.hasSpeed = false;
        result.speed_ = com.google.android.apps.mytracks.content.Sensor.SensorDataDouble.getDefaultInstance();
        return this;
      }
      
      // optional .com.google.android.apps.mytracks.content.SensorDataTriple accel = 7;
      public boolean hasAccel() {
        return result.hasAccel();
      }
      public com.google.android.apps.mytracks.content.Sensor.SensorDataTriple getAccel() {
        return result.getAccel();
      }
      public Builder setAccel(com.google.android.apps.mytracks.content.Sensor.SensorDataTriple value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasAccel = true;
        result.accel_ = value;
        return this;
      }
      public Builder setAccel(com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.Builder builderForValue) {
        result.hasAccel = true;
        result.accel_ = builderForValue.build();
        return this;
      }
      public Builder mergeAccel(com.google.android.apps.mytracks.content.Sensor.SensorDataTriple value) {
        if (result.hasAccel() &&
            result.accel_ != com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.getDefaultInstance()) {
          result.accel_ =
            com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.newBuilder(result.accel_).mergeFrom(value).buildPartial();
        } else {
          result.accel_ = value;
        }
        result.hasAccel = true;
        return this;
      }
      public Builder clearAccel() {
        result.hasAccel = false;
        result.accel_ = com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.getDefaultInstance();
        return this;
      }
      
      // optional .com.google.android.apps.mytracks.content.SensorDataTriple magnetic_field = 8;
      public boolean hasMagneticField() {
        return result.hasMagneticField();
      }
      public com.google.android.apps.mytracks.content.Sensor.SensorDataTriple getMagneticField() {
        return result.getMagneticField();
      }
      public Builder setMagneticField(com.google.android.apps.mytracks.content.Sensor.SensorDataTriple value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasMagneticField = true;
        result.magneticField_ = value;
        return this;
      }
      public Builder setMagneticField(com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.Builder builderForValue) {
        result.hasMagneticField = true;
        result.magneticField_ = builderForValue.build();
        return this;
      }
      public Builder mergeMagneticField(com.google.android.apps.mytracks.content.Sensor.SensorDataTriple value) {
        if (result.hasMagneticField() &&
            result.magneticField_ != com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.getDefaultInstance()) {
          result.magneticField_ =
            com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.newBuilder(result.magneticField_).mergeFrom(value).buildPartial();
        } else {
          result.magneticField_ = value;
        }
        result.hasMagneticField = true;
        return this;
      }
      public Builder clearMagneticField() {
        result.hasMagneticField = false;
        result.magneticField_ = com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.getDefaultInstance();
        return this;
      }
      
      // optional .com.google.android.apps.mytracks.content.SensorDataTriple gyro = 9;
      public boolean hasGyro() {
        return result.hasGyro();
      }
      public com.google.android.apps.mytracks.content.Sensor.SensorDataTriple getGyro() {
        return result.getGyro();
      }
      public Builder setGyro(com.google.android.apps.mytracks.content.Sensor.SensorDataTriple value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGyro = true;
        result.gyro_ = value;
        return this;
      }
      public Builder setGyro(com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.Builder builderForValue) {
        result.hasGyro = true;
        result.gyro_ = builderForValue.build();
        return this;
      }
      public Builder mergeGyro(com.google.android.apps.mytracks.content.Sensor.SensorDataTriple value) {
        if (result.hasGyro() &&
            result.gyro_ != com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.getDefaultInstance()) {
          result.gyro_ =
            com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.newBuilder(result.gyro_).mergeFrom(value).buildPartial();
        } else {
          result.gyro_ = value;
        }
        result.hasGyro = true;
        return this;
      }
      public Builder clearGyro() {
        result.hasGyro = false;
        result.gyro_ = com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.getDefaultInstance();
        return this;
      }
      
      // optional .com.google.android.apps.mytracks.content.SensorDataTriple gravity = 10;
      public boolean hasGravity() {
        return result.hasGravity();
      }
      public com.google.android.apps.mytracks.content.Sensor.SensorDataTriple getGravity() {
        return result.getGravity();
      }
      public Builder setGravity(com.google.android.apps.mytracks.content.Sensor.SensorDataTriple value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGravity = true;
        result.gravity_ = value;
        return this;
      }
      public Builder setGravity(com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.Builder builderForValue) {
        result.hasGravity = true;
        result.gravity_ = builderForValue.build();
        return this;
      }
      public Builder mergeGravity(com.google.android.apps.mytracks.content.Sensor.SensorDataTriple value) {
        if (result.hasGravity() &&
            result.gravity_ != com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.getDefaultInstance()) {
          result.gravity_ =
            com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.newBuilder(result.gravity_).mergeFrom(value).buildPartial();
        } else {
          result.gravity_ = value;
        }
        result.hasGravity = true;
        return this;
      }
      public Builder clearGravity() {
        result.hasGravity = false;
        result.gravity_ = com.google.android.apps.mytracks.content.Sensor.SensorDataTriple.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.google.android.apps.mytracks.content.SensorDataSet)
    }
    
    static {
      defaultInstance = new SensorDataSet(true);
      com.google.android.apps.mytracks.content.Sensor.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.google.android.apps.mytracks.content.SensorDataSet)
  }
  
  
  static {
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
